# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QUtility
                                 A QGIS plugin
 Un toolbox multifunzione per QGIS: rinomina layer, cambia tipi di campo, importa shapefile da ZIP e altro ancora, tutto in pochi clic.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-06
        copyright            : (C) 2025 by Lorenzo Alunni
        email                : gis@eagleprojects.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QUtility class from file QUtility.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qutility import QUtility
    return QUtility(iface)
